spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:payment-scheduler
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
      DB_CLOSE_ON_EXIT: FALSE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    allow-bean-definition-overriding: true
      
springdoc:
  swagger-ui:
     path: /swagger-ui.html
  show-actuator: true
  packagesToScan: com.flexpag.paymentscheduler
  
  boot:
   admin:
     client:
      url: http://localhost:8081
 
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
      defaults: enabled
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "@project.name@"
    version: "@project.version@"
    description:  "@project.description@"
    enconding: "@project.build.sourceEncoding@"
    java: "@java.version@"


jwt:
  secret: A+X;fTJP&Pd,TD9dwVq(hsHX,ya^<wsD_UK7L+@=S;{'CydP]{v@}G'b>et;yz$*\yL5S8EJN:%P:X%H9>#nYLrX}@\s?CQcpspH,2emzBc!Q[V'AYa~uzF8WR~AUrMzxp/V$9([S9X#zj/CH('#]B_Hc+%fGhe27YB;^j4\Xk=Ju"Ap~_&<L;=!Z;!,2UP;!hF3P]j85#*`&T]/kB/W^6$v~u6qpejL>kY^f)sy4:qTq_Ec!-z!@aAp~sLKGU>$
  expiration: 86400000